//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICINE_BILLING
    {
        public int MEDICINE_BILLING_ID { get; set; }
        public int PHARMACY_BILLING_ID { get; set; }
        public int MedicineID { get; set; }
        public int Quantity { get; set; }
    
        public virtual PHARMACY_BILLING PHARMACY_BILLING { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
